InteractItemframes Flag and Command
Zone-Protect/Zone-protect pull request #73
Opened 2021-12-27 10:23 UTC by Lukamon24

Done #16

2021-12-27 10:24 UTC, mosemister commented on src/main/java/org/zone/commands/structure/region/flags/interact/itemframe/ZoneFlagInteractItemframesEnableDisableCommand.java
> +    public static final BooleanArgument ENABLEDISABLE = new BooleanArgument("enableValue", "enable", "disable");
interacty ItemFrame?

2021-12-27 10:27 UTC, Lukamon24 commented on src/main/java/org/zone/commands/structure/region/flags/interact/itemframe/ZoneFlagInteractItemframesEnableDisableCommand.java
> +    public static final BooleanArgument ENABLEDISABLE = new BooleanArgument("enableValue", "enable", "disable");
XD sorry keyboard problems

2021-12-27 10:28 UTC, mosemister requested changes
Just one argument id that im questioning but good otgerwise

2021-12-28 04:18 UTC, Lukamon24 commented
done dude

2021-12-28 09:45 UTC, mosemister commented on src/main/java/org/zone/commands/structure/region/flags/interact/itemframe/ZoneFlagInteractItemframesViewCommand.java
> +            .setLevel(GroupKeys.INTERACT_ITEMFRAME));
This should not check the level. If it doesnt have the flag then it should say that

2021-12-28 09:48 UTC, mosemister requested changes
One tiny change

2021-12-28 09:57 UTC, mosemister approved these changes
Approved

2021-12-28 09:58 UTC, merged